version: '3.9'
services:

  random-project:
    container_name: random-project
    image: node:18-alpine
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
